# Generated by Django 3.1 on 2022-01-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0002_auto_20220111_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Hi, I am using Hoodwatch', max_length=150),
        ),
    ]
